/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.jacksnapsmobile;

public final class R {
    public static final class attr {
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int backgroundColor=0x7f010000;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int keywords=0x7f010003;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int primaryTextColor=0x7f010001;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int refreshInterval=0x7f010004;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int secondaryTextColor=0x7f010002;
    }
    public static final class color {
        public static final int background=0x7f050000;
        public static final int caption_background=0x7f050001;
        public static final int caption_text=0x7f050002;
    }
    public static final class drawable {
        public static final int bg=0x7f020000;
        public static final int gradient=0x7f020001;
        public static final int icon=0x7f020002;
    }
    public static final class id {
        public static final int about=0x7f080003;
        public static final int about_content=0x7f080000;
        public static final int ad=0x7f080002;
        public static final int fetch_button=0x7f080001;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class menu {
        public static final int menu=0x7f070000;
    }
    public static final class string {
        public static final int about_shortcut=0x7f06000a;
        public static final int about_text=0x7f060005;
        public static final int about_title=0x7f060006;
        public static final int app_name=0x7f060000;
        public static final int fetch_error=0x7f060004;
        public static final int fetch_label=0x7f060002;
        public static final int fetch_notice=0x7f060003;
        public static final int main_title=0x7f060001;
        public static final int settings_label=0x7f060007;
        public static final int settings_shortcut=0x7f060009;
        public static final int settings_title=0x7f060008;
        public static final int text_summary=0x7f06000c;
        public static final int text_title=0x7f06000b;
    }
    public static final class xml {
        public static final int settings=0x7f040000;
    }
    public static final class styleable {
        /** Attributes that can be used with a com_admob_android_ads_AdView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_admob_android_ads_AdView_backgroundColor org.me.jacksnapsmobile:backgroundColor}</code></td><td></td></tr>
           <tr><td><code>{@link #com_admob_android_ads_AdView_keywords org.me.jacksnapsmobile:keywords}</code></td><td></td></tr>
           <tr><td><code>{@link #com_admob_android_ads_AdView_primaryTextColor org.me.jacksnapsmobile:primaryTextColor}</code></td><td></td></tr>
           <tr><td><code>{@link #com_admob_android_ads_AdView_refreshInterval org.me.jacksnapsmobile:refreshInterval}</code></td><td></td></tr>
           <tr><td><code>{@link #com_admob_android_ads_AdView_secondaryTextColor org.me.jacksnapsmobile:secondaryTextColor}</code></td><td></td></tr>
           </table>
           @see #com_admob_android_ads_AdView_backgroundColor
           @see #com_admob_android_ads_AdView_keywords
           @see #com_admob_android_ads_AdView_primaryTextColor
           @see #com_admob_android_ads_AdView_refreshInterval
           @see #com_admob_android_ads_AdView_secondaryTextColor
         */
        public static final int[] com_admob_android_ads_AdView = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004
        };
        /**
          <p>This symbol is the offset where the {@link org.me.jacksnapsmobile.R.attr#backgroundColor}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:backgroundColor
        */
        public static final int com_admob_android_ads_AdView_backgroundColor = 0;
        /**
          <p>This symbol is the offset where the {@link org.me.jacksnapsmobile.R.attr#keywords}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:keywords
        */
        public static final int com_admob_android_ads_AdView_keywords = 3;
        /**
          <p>This symbol is the offset where the {@link org.me.jacksnapsmobile.R.attr#primaryTextColor}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:primaryTextColor
        */
        public static final int com_admob_android_ads_AdView_primaryTextColor = 1;
        /**
          <p>This symbol is the offset where the {@link org.me.jacksnapsmobile.R.attr#refreshInterval}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:refreshInterval
        */
        public static final int com_admob_android_ads_AdView_refreshInterval = 4;
        /**
          <p>This symbol is the offset where the {@link org.me.jacksnapsmobile.R.attr#secondaryTextColor}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:secondaryTextColor
        */
        public static final int com_admob_android_ads_AdView_secondaryTextColor = 2;
    };
}
